### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by NetoSantoos78** [NotMarra/NotCredits#8]
[NotCredits] Enabling NotCredits v2.5
[21:29:50] [Server thread/INFO]: [com.notmarra.notcredits.hikari.HikariDataSource] NotCredits - Starting...
[21:29:50] [Server thread/INFO]: [com.notmarra.notcredits.hikari.HikariDataSource] NotCredits - Start completed.
[21:29:50] [Server thread/ERROR]: Error occurred while enabling NotCredits v2.5 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at NotCredits-2.5.jar/com.notmarra.notcredits.Notcredits.getNMSHandler(Notcredits.java:122) ~[NotCredits-2.5.jar:?]
	at NotCredits-2.5.jar/com.notmarra.notcredits.Notcredits.onEnable(Notcredits.java:41) ~[NotCredits-2.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by NotMarra** [comment]
Can you give me more information? What server version and paper version are you using? It will be helpful.

**Comment by NotMarra** [comment]
Done, it was bukkit, I didn't notice that they changed the nms retrieval style (they removed it completely if I'm not mistaken) so I changed it, I tested it on older versions and everything should work again.

**Comment by NetoSantoos78** [comment]
I'm on build 82 of paper
